<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>MonarchLauncher.App</AssemblyName>
    <RootNamespace>MonarchLauncher.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.3.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\monarch-logo.png" />
    <Content Include="launcher-settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
